
# About the project


This project consists of coursework completed on the **PHD-302 Introduction to Open Data Science** course. It will consist of weekly assingments that will compiled into a learning diary. 

The following project is stored in Github, and can be found can be found from the following URL:\
<link url> https://github.com/TSamJ/IODS-project

1.

Everything seems to be in working order with the repository, course diary and local folder being accounted for. 

2. 

I am feeling like a PhD-student: tired, stressed and equipped with an imposter-syndrome big enough to black out the sun. So everything is in order in that regard. But I am feeling very positive about this course. I have recently
started working with big datasets and getting to know R. I hope to learn much more about statistical tests, clustering and dimensionality reduction such as PCA. I'm fairly confident that this course will eventually save me tons of time and even much more nerves, as finding solutions from stackoverflow does very little to actually familiarize a beginner
with the root cause of the issues. 

I found this course while browsing the uni course catalogue in hopes of finding something that is actually relevant for me at this point. And this is exactly what I needed although I do worry that this could go, like so many coding courses do, right back to the endless stackoverflow swamp when the pace picks up.

Personally, I feel slightly sceptical about the R markdown: it seems like a somewhat convoluted way of achieving relatively little of use at this point. And also
much like a tool that I would never personally use in context of scientific research and publication. It's a bit like writing a document in latex in the sense that
it's a tool with some potential and I can see use cases where it would become extremely handy, but is such a niche use, that more common approaches are usually just easier. I have hard time imaging a situation where I would like to
have a ready made word or pdf instead of a separate images/ plots that I can then use in whatever text editor I choose. 

This combined with github, that I would personally rename as "the dark, sad pit of dysfunctionality and despair" makes it obvious that making sense of github will be the main early challenge of this course.

The R for Health Data Science looks extremely promising at this point.  The chapters so far have been intuitive and the syntax has been explained if not well, atleast much better
than in most tutorials one easily runs into while using search engines. The topics relevant to me in my own work that were present in the early chapters I was previously mostly familiar
with but I was happy to get a better grasp of the reasoning behind some commands/ functionality. And some new solutions as well that will hopefully help me to speed up my workflow.
I do not know how the book compares to stack overflow. Naturally, it will be less hands on and thus slightly less effective as a learning tool, but then again, I believe
that in the long run it will serve as a much nicer resource to refer back to. So far, I've mostly appreciated the somewhat good explanations between different basic commands, but 
feel they could do more here. For example `case_when` is ignored but highly useful. Also, can I do conditional statements between two dataframes without joining? Is there a workaround to get multiple values on the same axis with unique free scales?

3. 

Index.Rmd has been updated with the author name. Would this not be a more logical place for the github link?

4. 

I followed the instruction and generated a new token. However, as I had previously generated a token during the initial setup of Git / Rstudio interaction, I already had an associated token password and was able to push to git prior to completing the step. Thus I was not able to give the password to the console, just review my previously set token.

5. 

Test pushes have been succesful. 

6. 

The results are hopefully visible, if github ever updates. 




